### ISSUE TITLE
wps签到失败

### ISSUE THREAD

**Issue by Deepturn** [poboll/wps_script#4]
wps在填入cookie中wps_sid的值后，签到失败，有成功案例吗？

**Comment by leiting7273** [comment]
我也签到失败，应该是滑块验证码的问题，这个代码是提交的固定坐标值，不知道怎么解决

**Comment by ypq123456789** [comment]
你们也是这个错误吗


16:41:57.582
通知
脚本环境初始化...
<system>
16:41:58.596
通知
已开始执行
<system>
16:41:58.636
信息
激活工作表：CONFIG
wps_light.js.js:266:13
16:41:58.637
信息
开始读取主配置表
wps_light.js.js:35:11
16:41:58.676
信息
激活工作表：PUSH
wps_light.js.js:266:13
16:41:58.676
信息
开始读取推送工作表
wps_light.js.js:67:11
16:41:58.711
信息
开始读取邮箱配置
wps_light.js.js:208:11
16:41:58.714
信息
激活工作表：wps
wps_light.js.js:266:13
16:41:58.714
信息
开始读取分配置表
wps_light.js.js:90:11
16:41:58.831
信息
{"result":"error","data":"","msg":"need_captcha"}
wps_light.js.js:326:13
16:42:00.832
信息
单元格A2need_captcha,签到成功
wps_light.js.js:337:11
16:42:05.970
通知
执行完毕

**Comment by Deepturn** [comment]
搞不懂啊

**Comment by poboll** [comment]
需要滑块验证码。轻量版不稳定，您第一天先手动签到，明天再尝试运行下脚本。
WPS客户端版本签到暂时无法解决。
最新版本已修复稻壳自动签到且无法领取PPT的功能，更新可选择是否将领取到的PPT自动转存到“WPS云文档”。
